package cloud.fogbow.cli.constants;

public class Documentation {
    public class Allocation {
        public static final String GET = "Gets the user's current resource allocation on the specified member and cloud.";
    }

    public class Clouds {
    }

    public class CommonParameters {
        public static final String CLOUD_NAME = "Name of the cloud to which the request is targeted.";
        public static final String COMPUTE_ID_PARAMETER = "Compute Id";
        public static final String SYSTEM_USER_TOKEN = "User's token (generated by token command).";
        public static final String SYSTEM_USER_TOKEN_PATH = "Path to file containing the user's token (generated by token command).";
        public static final String MEMBER_ID = "Id of the member to which the request is to be sent.";
        public static final String PROVIDER = "Provider";
        public static final String PUBLIC_IPS_COMPUTE_ID = "Id of the compute to associate this ip with";
        public static final String URL = "URL of the Fogbow service.";
    }

    public class Compute {
        public static final String USER_DATA = "User data option. in the format <path/to/cloudinit/file>:<file_format>. type --list-cloudinit to see available formats.";
    }

    public class FederatedNetwork {
        public static final String ID = "Federated network identification.";
    }

    public class GenericRequest {
        public static final String BODY = "Body field.";
        public static final String HEADERS = "Headers field.";
        public static final String METHOD = "Method field.";
        public static final String URL = "URL field.";
    }

    public class Image {
        public static final String GET = "Gets details for a specific image.";
        public static final String GET_ALL = "Gets the list of all images available.";
        public static final String ID = "Image identifier.";
    }

    public class Member {
        public static final String GET_ALL = "Gets the list of members that belong to the federation.";
    }

    public class Order {
        public static final String CREATE = "Creates the specified resource.";
        public static final String DELETE = "Deletes the resource.";
        public static final String GET = "Gets the details of the resource.";
        public static final String GET_ALL = "Gets the list of all resources created by the user.";
        public static final String ID = "Resource identifier.";
    }

    public class Quota {
        public static final String GET = "Gets the user's quota on the specified member and cloud.";
    }

    public class SecurityGroupRule {

    }

    public class Token {
        public static final String COMMAND_DESCRIPTION = "Creates tokens.";
        public static final String CREATE_COMMAND = "Creates a new token.";
        public static final String DYNAMIC_PARAMS = "Dynamic parameters for token command.";
        public static final String PUBLIC_KEY_PARAMETER = "Public key used to sign the new token.";
        public static final String PUBLIC_KEY_PATH_PARAMETER = "Path tp the public key used to sign the new token.";
    }
}

